### ISSUE TITLE
Does not work on OSX

### ISSUE THREAD

**Issue by codeboost** [saneki/node-toxcore#13]
When trying to run the examples, I keep getting this fatal error on OSX:

Error: Dynamic Symbol Retrieval Error: dlsym(0x10130d980, tox_add_tcp_relay): symbol not found

Here's the call stack:
	
	Error: Dynamic Symbol Retrieval Error: dlsym(0x10130d980, tox_add_tcp_relay): symbol not found
    at DynamicLibrary.get (/Users/florin/code/temp/node-toxcore/examples/node_modules/toxcore/node_modules/ffi/lib/dynamic_library.js:112:11)
    at /Users/florin/code/temp/node-toxcore/examples/node_modules/toxcore/node_modules/ffi/lib/library.js:50:19
    at Array.forEach (native)
    at Object.Library (/Users/florin/code/temp/node-toxcore/examples/node_modules/toxcore/node_modules/ffi/lib/library.js:47:28)
    at Tox.createLibrary (/Users/florin/code/temp/node-toxcore/examples/node_modules/toxcore/lib/tox.js:185:14)
    at new Tox (/Users/florin/code/temp/node-toxcore/examples/node_modules/toxcore/lib/tox.js:131:24)
    at Object.<anonymous> (/Users/florin/code/temp/node-toxcore/examples/bin/file-transfer-example.js:28:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

**Comment by codeboost** [comment]
I had an older version of toxcore on my computer, hence the dlsym erorr.
Fixed it by installing the lastest libtoxcore version, like this:

	brew tap Tox/tox
	brew install --HEAD libtoxcore

Would be good to mention that you need toxcore library installed before using node-toxcore, for absolute beginners to toxcore like myself. I assumed that npm install does it automatically.
